language: node_js
script:
  echo "skipping tests"
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "symmlink.com"
  skip_cleanup: true
  region: "us-east-1"
  local_dir: app
notifications:
      email:
          on_failure: always